name: Auto Generate and Commit Finalplay.m3u

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - sources.txt
      - update_playlist.js
      - .github/workflows/auto-commit.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master  # âœ… Checkout branch 'master'

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: â–¶ï¸ Run update_playlist.js
        env:
          GH_TOKEN: ${{ secrets.NODEJS }}       # Secret token GitHub kamu
          GH_USERNAME: yourusername             # Ganti dengan username GitHub kamu
          GH_REPO: your-repo-name               # Ganti dengan nama repo kamu
        run: node update_playlist.js
